//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemadecompras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoCursos
    {
        public int Id { get; set; }
        public Nullable<int> idCurso { get; set; }
        public int idUsuario { get; set; }
        public System.DateTime FechaInscripcion { get; set; }
        public Nullable<bool> BitEliminado { get; set; }
    
        public virtual Cursos Cursos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
